/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Daniel
 */
public class FinalSolicitudFrances extends javax.swing.JFrame {

    /**
     * Creates new form FinalSolicitud
     */
    conexion.Conexion con = new Conexion();
    Connection cn = con.conectar();

    public FinalSolicitudFrances() {
        String nombres = lg.returnNombres();
        String apellidos = lg.returnApellidos();
        initComponents();
        colocarDatos();
        txtusuario.setText(nombres + " " + apellidos);
    }
    LogIn lg = new LogIn();
    Solicitar s = new Solicitar();
    DecimalFormat df = new DecimalFormat("#.00");

    public void colocarDatos() {

        JTcuotaOCP1.setText("$" + df.format(s.return12MesesFrances()));
        JTcuotaOCP2.setText("$" + df.format(s.return24MesesFrances()));
        JTcuotaOCP3.setText("$" + df.format(s.return36MesesFrances()));
        JTcuotaOCP4.setText("$" + df.format(s.return48MesesFrances()));
        JTcuotaOCP5.setText("$" + df.format(s.return60MesesFrances()));
        JTtotalOCP1.setText("$" + df.format(s.return12TotalFrances()));
        JTtotalOCP2.setText("$" + df.format(s.return24TotalFrances()));
        JTtotalOCP3.setText("$" + df.format(s.return36TotalFrances()));
        JTtotalOCP4.setText("$" + df.format(s.return48TotalFrances()));
        JTtotalOCP5.setText("$" + df.format(s.return60TotalFrances()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRUPO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JTcuotaOCP1 = new javax.swing.JTextField();
        JTtotalOCP1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        JTcuotaOCP2 = new javax.swing.JTextField();
        JTtotalOCP2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JTcuotaOCP3 = new javax.swing.JTextField();
        JTtotalOCP3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JTcuotaOCP4 = new javax.swing.JTextField();
        JTtotalOCP4 = new javax.swing.JTextField();
        JRopcion1 = new javax.swing.JRadioButton();
        JRopcion2 = new javax.swing.JRadioButton();
        JRopcion3 = new javax.swing.JRadioButton();
        JRopcion4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JTcuotaOCP5 = new javax.swing.JTextField();
        JTtotalOCP5 = new javax.swing.JTextField();
        JRopcion5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoCuenta.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconouser.png"))); // NOI18N

        txtusuario.setEditable(false);
        txtusuario.setBackground(new java.awt.Color(0, 204, 153));
        txtusuario.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        txtusuario.setForeground(new java.awt.Color(255, 255, 255));
        txtusuario.setToolTipText("");
        txtusuario.setBorder(null);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconoSalir.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ESCOJA UNA OPCIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("12 MESES");

        jLabel9.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CUOTAS:");

        jLabel10.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("TOTAL:");

        JTcuotaOCP1.setBackground(new java.awt.Color(204, 204, 204));
        JTcuotaOCP1.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTcuotaOCP1.setForeground(new java.awt.Color(0, 0, 0));
        JTcuotaOCP1.setBorder(null);
        JTcuotaOCP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuotaOCP1ActionPerformed(evt);
            }
        });

        JTtotalOCP1.setBackground(new java.awt.Color(204, 204, 204));
        JTtotalOCP1.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTtotalOCP1.setForeground(new java.awt.Color(0, 0, 0));
        JTtotalOCP1.setBorder(null);
        JTtotalOCP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtotalOCP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTcuotaOCP1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(14, 14, 14)
                        .addComponent(JTtotalOCP1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(JTcuotaOCP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(JTtotalOCP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(156, 142));

        jLabel5.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("24 MESES");

        jLabel11.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("TOTAL:");

        jLabel12.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("CUOTAS:");

        JTcuotaOCP2.setBackground(new java.awt.Color(204, 204, 204));
        JTcuotaOCP2.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTcuotaOCP2.setForeground(new java.awt.Color(0, 0, 0));
        JTcuotaOCP2.setBorder(null);
        JTcuotaOCP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuotaOCP2ActionPerformed(evt);
            }
        });

        JTtotalOCP2.setBackground(new java.awt.Color(204, 204, 204));
        JTtotalOCP2.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTtotalOCP2.setForeground(new java.awt.Color(0, 0, 0));
        JTtotalOCP2.setBorder(null);
        JTtotalOCP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtotalOCP2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTcuotaOCP2)
                    .addComponent(JTtotalOCP2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(JTcuotaOCP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTtotalOCP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(156, 142));

        jLabel6.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("36 MESES");

        jLabel13.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("TOTAL:");

        jLabel14.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("CUOTAS:");

        JTcuotaOCP3.setBackground(new java.awt.Color(204, 204, 204));
        JTcuotaOCP3.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTcuotaOCP3.setForeground(new java.awt.Color(0, 0, 0));
        JTcuotaOCP3.setBorder(null);
        JTcuotaOCP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuotaOCP3ActionPerformed(evt);
            }
        });

        JTtotalOCP3.setBackground(new java.awt.Color(204, 204, 204));
        JTtotalOCP3.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTtotalOCP3.setForeground(new java.awt.Color(0, 0, 0));
        JTtotalOCP3.setBorder(null);
        JTtotalOCP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtotalOCP3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTcuotaOCP3)
                    .addComponent(JTtotalOCP3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(JTcuotaOCP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTtotalOCP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setPreferredSize(new java.awt.Dimension(156, 142));

        jLabel7.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("48 MESES");

        jLabel15.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("TOTAL:");

        jLabel16.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("CUOTAS:");

        JTcuotaOCP4.setBackground(new java.awt.Color(204, 204, 204));
        JTcuotaOCP4.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTcuotaOCP4.setForeground(new java.awt.Color(0, 0, 0));
        JTcuotaOCP4.setBorder(null);
        JTcuotaOCP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuotaOCP4ActionPerformed(evt);
            }
        });

        JTtotalOCP4.setBackground(new java.awt.Color(204, 204, 204));
        JTtotalOCP4.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTtotalOCP4.setForeground(new java.awt.Color(0, 0, 0));
        JTtotalOCP4.setBorder(null);
        JTtotalOCP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtotalOCP4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTcuotaOCP4)
                    .addComponent(JTtotalOCP4, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(JTcuotaOCP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTtotalOCP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GRUPO.add(JRopcion1);
        JRopcion1.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JRopcion1.setForeground(new java.awt.Color(0, 0, 0));
        JRopcion1.setText("OPCIÓN 1");
        JRopcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRopcion1ActionPerformed(evt);
            }
        });

        GRUPO.add(JRopcion2);
        JRopcion2.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JRopcion2.setForeground(new java.awt.Color(0, 0, 0));
        JRopcion2.setText("OPCIÓN 2");

        GRUPO.add(JRopcion3);
        JRopcion3.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JRopcion3.setForeground(new java.awt.Color(0, 0, 0));
        JRopcion3.setText("OPCIÓN 3");

        GRUPO.add(JRopcion4);
        JRopcion4.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JRopcion4.setForeground(new java.awt.Color(0, 0, 0));
        JRopcion4.setText("OPCIÓN 4");
        JRopcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRopcion4ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("60 MESES");

        jLabel17.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("TOTAL:");

        jLabel18.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("CUOTAS:");

        JTcuotaOCP5.setBackground(new java.awt.Color(204, 204, 204));
        JTcuotaOCP5.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTcuotaOCP5.setForeground(new java.awt.Color(0, 0, 0));
        JTcuotaOCP5.setBorder(null);
        JTcuotaOCP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTcuotaOCP5ActionPerformed(evt);
            }
        });

        JTtotalOCP5.setBackground(new java.awt.Color(204, 204, 204));
        JTtotalOCP5.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JTtotalOCP5.setForeground(new java.awt.Color(0, 0, 0));
        JTtotalOCP5.setBorder(null);
        JTtotalOCP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTtotalOCP5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTcuotaOCP5)
                    .addComponent(JTtotalOCP5, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JTcuotaOCP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTtotalOCP5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        GRUPO.add(JRopcion5);
        JRopcion5.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        JRopcion5.setForeground(new java.awt.Color(0, 0, 0));
        JRopcion5.setText("OPCIÓN 5");
        JRopcion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRopcion5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 153));
        jButton1.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("FINALIZAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JRopcion5))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(403, 403, 403)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(JRopcion1))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(JRopcion2)
                                .addGap(109, 109, 109)
                                .addComponent(JRopcion3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JRopcion4)
                                .addGap(34, 34, 34))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRopcion3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JRopcion1)
                        .addComponent(JRopcion2))
                    .addComponent(JRopcion4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(JRopcion5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed

    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        String telefono = String.valueOf(evt.getKeyChar());
        if (!telefono.matches("[0-9]")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtusuarioKeyTyped

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        LogIn log = new LogIn();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void JRopcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRopcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRopcion1ActionPerformed

    private void JRopcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRopcion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRopcion4ActionPerformed

    private void JRopcion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRopcion5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRopcion5ActionPerformed

    private void JTcuotaOCP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuotaOCP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuotaOCP1ActionPerformed

    private void JTtotalOCP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtotalOCP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtotalOCP1ActionPerformed

    private void JTcuotaOCP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuotaOCP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuotaOCP2ActionPerformed

    private void JTtotalOCP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtotalOCP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtotalOCP2ActionPerformed

    private void JTcuotaOCP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuotaOCP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuotaOCP3ActionPerformed

    private void JTtotalOCP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtotalOCP3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtotalOCP3ActionPerformed

    private void JTcuotaOCP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuotaOCP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuotaOCP4ActionPerformed

    private void JTtotalOCP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtotalOCP4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtotalOCP4ActionPerformed

    private void JTcuotaOCP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTcuotaOCP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTcuotaOCP5ActionPerformed

    private void JTtotalOCP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTtotalOCP5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTtotalOCP5ActionPerformed

    public String fechaFinal(int anio) {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        Calendar cal = Calendar.getInstance();
        cal.add(Calendar.YEAR, anio);
        Date modifiedDate = cal.getTime();
        return formatoFecha.format(modifiedDate);
    }

    public String fechaActual() {
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
        return formatoFecha.format(fecha);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double cuota = 0;
        double total = 0;
        int plazoPrestamo = 0;
        String fechaFinal = "";
        String fechaActual = fechaActual();
        String Sistema = "Francés";
        double valorPres = 0;
        int nroCuota = 0;
        double interes = 0;
        double amortizacion = 0;
        double valorInteres = 0;
        double tasaInteres = s.TasaInteres();
        double importeCrd = s.monto();
        int idUsuario = lg.returnIdUsuario();
        if (JRopcion1.isSelected()) {
            cuota = s.return12MesesFrances();
            total = s.return12TotalFrances();
            plazoPrestamo = 12 / 12;
            nroCuota = 12;
            fechaFinal = fechaFinal(1);
            for(int i=1; i<= nroCuota; i++){
                interes = importeCrd * tasaInteres;
                amortizacion = cuota - interes;
                importeCrd = importeCrd - amortizacion;
                valorInteres += interes;
                valorPres += amortizacion;
            }
        } else if (JRopcion2.isSelected()) {
            cuota = s.return24MesesFrances();
            total = s.return24TotalFrances();
            plazoPrestamo = 24 / 12;
            nroCuota = 24;
            fechaFinal = fechaFinal(2);
            for(int i=1; i<= nroCuota; i++){
                interes = importeCrd * tasaInteres;
                amortizacion = cuota - interes;
                importeCrd = importeCrd - amortizacion;
                valorInteres += interes;
                valorPres += amortizacion;
            }
        } else if (JRopcion3.isSelected()) {
            cuota = s.return36MesesFrances();
            total = s.return36TotalFrances();
            plazoPrestamo = 36 / 12;
            nroCuota = 36;
            fechaFinal = fechaFinal(3);
            for(int i=1; i<= nroCuota; i++){
                interes = importeCrd * tasaInteres;
                amortizacion = cuota - interes;
                importeCrd = importeCrd - amortizacion;
                valorInteres += interes;
                valorPres += amortizacion;
            }
        } else if (JRopcion4.isSelected()) {
            cuota = s.return48MesesFrances();
            total = s.return48TotalFrances();
            plazoPrestamo = 48 / 12;
            nroCuota = 48;
            fechaFinal = fechaFinal(4);
            for(int i=1; i<= nroCuota; i++){
                interes = importeCrd * tasaInteres;
                amortizacion = cuota - interes;
                importeCrd = importeCrd - amortizacion;
                valorInteres += interes;
                valorPres += amortizacion;
            }
        } else if (JRopcion5.isSelected()) {
            cuota = s.return60MesesFrances();
            total = s.return60TotalFrances();
            plazoPrestamo = 60 / 12;
            nroCuota = 60;
            fechaFinal = fechaFinal(5);
            for(int i=1; i<= nroCuota; i++){
                interes = importeCrd * tasaInteres;
                amortizacion = cuota - interes;
                importeCrd = importeCrd - amortizacion;
                valorInteres += interes;
                valorPres += amortizacion;
            }
        }
        String SQL = "INSERT INTO prestamo (id_usuario, plazo_prestamo, fecha_emision, fecha_final, sistema_A, total_pagar, valor_cuota, nro_coutas, tasa_int, importe_crd) VALUES (" + idUsuario + ", " + plazoPrestamo + ", DATE('" + fechaActual + "'), DATE('" + fechaFinal + "'), '" + Sistema + "', " + total + ", " + cuota + ", " + nroCuota + ", " + tasaInteres + ", " + importeCrd + ");";
        String SQLIDPRESTAMO = "SELECT id_prestamo FROM prestamo ORDER BY id_prestamo DESC LIMIT 1;";
        Usuario.interes = valorInteres;
        Usuario.capital = valorPres;
        
        try {
            PreparedStatement ps = cn.prepareStatement(SQL);
            ps.executeUpdate();
            
            ps = cn.prepareStatement(SQLIDPRESTAMO);
            int idPrestamo = 0;
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                idPrestamo = rs.getInt("id_prestamo");
            }
            String SQLCUOTA = "INSERT INTO cuota (id_prestamo, Monto_Pagar, Valor_Pres, Valor_Interes) VALUES("+idPrestamo+", "+cuota+", "+valorPres+", "+valorInteres+");";
            ps = cn.prepareStatement(SQLCUOTA);
            ps.executeUpdate();
            String SQLIDCUOTA = "SELECT id_cuota FROM cuota ORDER BY id_cuota DESC LIMIT 1;";
            ps = cn.prepareStatement(SQLIDCUOTA);
            int idCuota = 0;
            rs = ps.executeQuery();
            if (rs.next()) {
                idCuota = rs.getInt("id_cuota");
            }
            String SQLCUOTAP = "INSERT INTO cuota_pagada (id_cuota, id_usuario, fecha_pago) VALUES("+idCuota+", "+idUsuario+", DATE('"+fechaActual+"'));";
            ps = cn.prepareStatement(SQLCUOTAP);
            ps.executeUpdate();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        JOptionPane.showMessageDialog(null, "PRESTAMO REALIZADO");
        CuentaCiudadano cuenta = new CuentaCiudadano();
        cuenta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public double returnInteres(){
        return Usuario.interes;
    }
    
    public double returnCapital(){
        return Usuario.capital;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalSolicitudFrances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalSolicitudFrances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalSolicitudFrances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalSolicitudFrances.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalSolicitudFrances().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GRUPO;
    private javax.swing.JRadioButton JRopcion1;
    private javax.swing.JRadioButton JRopcion2;
    private javax.swing.JRadioButton JRopcion3;
    private javax.swing.JRadioButton JRopcion4;
    private javax.swing.JRadioButton JRopcion5;
    private javax.swing.JTextField JTcuotaOCP1;
    private javax.swing.JTextField JTcuotaOCP2;
    private javax.swing.JTextField JTcuotaOCP3;
    private javax.swing.JTextField JTcuotaOCP4;
    private javax.swing.JTextField JTcuotaOCP5;
    private javax.swing.JTextField JTtotalOCP1;
    private javax.swing.JTextField JTtotalOCP2;
    private javax.swing.JTextField JTtotalOCP3;
    private javax.swing.JTextField JTtotalOCP4;
    private javax.swing.JTextField JTtotalOCP5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
